### ISSUE TITLE
cylon is at 1.0, disco requires <1

### ISSUE THREAD

**Issue by finson** [lorenwest/cylon-robot-disco#1]
```
npm ERR! peerinvalid The package cylon does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer cylon-robot-disco@0.1.6 wants cylon@>=0.22.0 < 1
```

**Comment by lorenwest** [comment]
It appears you may have a version of Cylon that isn't compatible with cylon-robot-disco (less than 0.22.0).

Cylon changed some internals that cylon-robot-disco used, and it only works with 0.22.0 or later.

**Comment by finson** [comment]
Loren:

Thanks for the quick reply.  I am running cylon 1.0 but disco is looking for <1.  At least I think that's what is happening!  Here's the installation output.

```
holly:~/repos/fountain/dam-core/Disco$ sudo npm install cylon-robot-disco
Password:
npm WARN peerDependencies The peer dependency cylon@>=0.22.0 < 1 included from cylon-robot-disco will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "cylon-robot-disco"
npm ERR! node v0.10.25
npm ERR! npm  v2.7.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package cylon does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer cylon-robot-disco@0.1.6 wants cylon@>=0.22.0 < 1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Finson/repos/fountain/dam-core/Disco/npm-debug.log
holly:~/repos/fountain/dam-core/Disco$
```

And here is the module list afterwards.

```
holly:~/repos/fountain/dam-core/Disco$ sudo npm list -depth 1
/Users/Finson/repos/fountain/dam-core/Disco
├─┬ cylon@1.0.0 peer invalid
│ └── async@0.9.0
├─┬ cylon-api-http@0.3.0
│ ├── body-parser@1.12.2
│ ├── express@4.12.3
│ ├── lodash@3.6.0
│ └── robeaux@0.4.1
├─┬ cylon-ble@0.5.0
│ ├── async@0.9.0
│ └── noble@0.3.14
└─┬ cylon-robot-disco@0.1.6
  ├── bluebird@2.9.24
  ├── clone@1.0.2
  ├── deep-extend@0.3.3
  ├── eventsource@0.1.6
  ├── node-discover@0.0.17
  ├── node-uuid@1.4.3
  └── request@2.55.0

npm ERR! peer invalid: cylon@1.0.0 /Users/Finson/repos/fountain/dam-core/Disco/node_modules/cylon
holly:~/repos/fountain/dam-core/Disco$
```

**Comment by lorenwest** [comment]
That's it!  I haven't moved cylon-robot-disco into the 1.0 world.

I can't guarantee getting to this right away, as my day job is pretty
hectic, so if you'd like to give it a try that'd be great.  If I don't get
to it in a couple weeks, you can give me a poke and see where I am.

Thanks for calling this out.

**Comment by finson** [comment]
Thanks Loren.  My time is kind of spotty too, but it will be interesting to take a look at the code.  One way or another, it'll be fixed in a couple of weeks!  Doug

**Comment by lorenwest** [comment]
Hi Doug,

Just pushed cylon-robot-disco v1.0.0, which is now compatible with cylon v1.x.  Let me know if you have any issues.

Cheers,
-Loren

**Comment by finson** [comment]
Thanks Loren.  So far so good!  Doug

> holly:~/repos/fountain/dam-core/Disco$ npm list -depth 1
> /Users/Finson/repos/fountain/dam-core/Disco
> ├─┬ cylon@1.0.0
> │ └── async@0.9.0
> ├─┬ cylon-api-http@0.3.0
> │ ├── body-parser@1.12.2
> │ ├── express@4.12.3
> │ ├── lodash@3.6.0
> │ └── robeaux@0.4.1
> ├─┬ cylon-ble@0.5.0
> │ ├── async@0.9.0
> │ └── noble@0.3.14
> └─┬ cylon-robot-disco@1.0.0
>   ├── bluebird@2.9.24
>   ├── clone@1.0.2
>   ├── deep-extend@0.3.3
>   ├── eventsource@0.1.6
>   ├── node-discover@0.0.17
>   ├── node-uuid@1.4.3
>   └── request@2.55.0
> 
> holly:~/repos/fountain/dam-core/Disco$
